version: "3.7"
services:
  storage:
    image: postgres:11
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: ${STORAGE_USER}
      POSTGRES_PASSWORD: ${STORAGE_PASSWORD}
      POSTGRES_DB: ${STORAGE_DB}
      POSTGRES_HOST: ${STORAGE_HOST}

  init:
    build: .
    image: cjbhub/macroscope-init
    environment: 
      DB_HOST: ${STORAGE_HOST}
      DB_NAME: ${STORAGE_DB}
      DB_USER: ${STORAGE_USER}
      DB_PASS: ${STORAGE_PASSWORD}
