version: "3.7"
services:
  storage:
    image: postgres:11
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: ${STORAGE_USER}
      POSTGRES_PASSWORD: ${STORAGE_PASSWORD}
      POSTGRES_DB: ${STORAGE_DB}
      POSTGRES_HOST: ${STORAGE_HOST}

  init:
    build: .
    image: cjbhub/macroscope-init
    environment: 
      DB_HOST: ${STORAGE_HOST}
      DB_NAME: ${STORAGE_DB}
      DB_USER: ${STORAGE_USER}
      DB_PASS: ${STORAGE_PASSWORD}
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${STORAGE_USER}:${STORAGE_PASSWORD}@${STORAGE_HOST}/${STORAGE_DB}
      PGRST_DB_ANON_ROLE: macroscope_anon
      PGRST_DB_SCHEMA: warehouse

